### PR TITLE
Sagas not updating

### PR DESCRIPTION
**Pull request by abeven**
Little typo on the 2.0 driver branch, the UpdateDefinition was only doing the $inc on version.

### CODE REVIEW

**Comment by tekmaven** [comment]
Why "breaking build on purpose"?

**Comment by abeven** [comment]
Whoops did you end up with that check in too?

**Comment by tekmaven** [comment]
Yep!  Just revert the commit and I can merge your PR.  

Thanks for the contribution! :+1:

**Comment by tekmaven** [comment]
Thanks @abeven.  I've merged the commit and additional unit testing in this area.

**Pull request closed without merging**
